# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ai2Ib6q8YdB5t7beX7cWVe-qMybF676F
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

df = pd.read_csv('pixel_data.csv')

def aplicar_transformacao(df, matriz, titulo):
    x_c = df['X'] - 25
    y_c = df['Y'] - 25

    coords = np.vstack((x_c, y_c))

    novas_coords = matriz @ coords

    x_novo = novas_coords[0, :] + 25
    y_novo = novas_coords[1, :] + 25

    plt.figure(figsize=(6, 6))
    plt.scatter(x_novo, y_novo, c=df[['R', 'G', 'B']].values/255.0, s=2)
    plt.gca().invert_yaxis()
    plt.title(titulo)
    plt.axis('equal')
    plt.axis('off')
    plt.show()

M_identidade = np.array([[1, 0],
                         [0, 1]])

M_escalonamento = np.array([[1.5, 0],
                            [0, 0.5]])

M_cisalhamento = np.array([[1, 0.5],
                           [0, 1]])

theta = math.radians(45)
M_rotacao = np.array([[math.cos(theta), -math.sin(theta)],
                      [math.sin(theta), math.cos(theta)]])

M_colapso = np.array([[1, 0],
                      [0, 0]])

aplicar_transformacao(df, M_identidade, 'Original')
aplicar_transformacao(df, M_escalonamento, 'Escalonamento (Largo e Achatado)')
aplicar_transformacao(df, M_cisalhamento, 'Cisalhamento no Eixo X')
aplicar_transformacao(df, M_rotacao, 'Rotação de 45 Graus')
aplicar_transformacao(df, M_colapso, 'Colapso Dimensional (Projeção no Eixo X)')